#ifndef BLE_HID_APP_CONFIG_H
#define BLE_HID_APP_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

#include "CONFIG.h"

#define BLE_HID_APP_DEFAULT_HID_IDLE_TIMEOUT 60000UL
#define BLE_HID_APP_DEFAULT_PASSCODE         0UL
#define BLE_HID_APP_DEFAULT_PAIRING_MODE     GAPBOND_PAIRING_MODE_INITIATE
#define BLE_HID_APP_DEFAULT_MITM_MODE        FALSE
#define BLE_HID_APP_DEFAULT_BONDING_MODE     TRUE
#define BLE_HID_APP_DEFAULT_IO_CAPABILITIES  GAPBOND_IO_CAP_NO_INPUT_NO_OUTPUT
#define BLE_HID_APP_DEFAULT_BATT_CRITICAL_LEVEL 6U
#define BLE_HID_APP_DEFAULT_ADVERTISING_ENABLED TRUE

#define BLE_GAP_POLICY_PARAM_UPDATE_ENABLED     1
#define BLE_GAP_POLICY_PARAM_UPDATE_DELAY_MS    12800UL
#define BLE_GAP_POLICY_CONN_INTERVAL_MIN        8U
#define BLE_GAP_POLICY_CONN_INTERVAL_MAX        8U
#define BLE_GAP_POLICY_CONN_LATENCY             0U
#define BLE_GAP_POLICY_CONN_TIMEOUT             500U

#ifdef __cplusplus
}
#endif

#endif
